### Load Dataset 
y = 0.3(w) * x

In [66]:
import numpy as np

In [67]:
x1 = np.random.uniform(low = -1.0, high = 1.0, size = 100)  ## uniform distribution 


print(x1.shape)
x1[:10]

(100,)


array([-0.34116805,  0.88030514, -0.24372275, -0.13107826,  0.72047141,
       -0.46770595, -0.81556937, -0.11333545,  0.30322765, -0.61047795])

In [80]:
x2 = np.random.uniform(low = -1.0, high = 1.0, size = 100)  ## uniform distribution 


print(x2.shape)
x2[:10]

(100,)


array([-0.15023147,  0.45373934, -0.69773579, -0.77133318, -0.59449272,
        0.16721176, -0.46444847, -0.37763371, -0.00135709,  0.15476108])

In [91]:
y = 0.3 * x1 + 0.5 * x2 + 0.1 ## add bias, x3 is always 1
#y = 0.3 * x1 + 0.5 * x2 + 0.1 * x3 ## add bias, x3 is always 1

print(y.shape)
y[:10]

(100,)


array([-0.07746615,  0.59096121, -0.32198472, -0.32499007,  0.01889506,
        0.04329409, -0.37689505, -0.12281749,  0.19028975, -0.00576284])

### Random Search(2-4)

In [69]:
num_epoch = 100
for epoch in range(num_epoch):
    w1 = np.random.uniform(low = -1.0, high = 1.0)
    #w1 = 0.3  # for test 
    y_predict = w1 *x1 ## we expect w1 is 0.3
    
    error = (y_predict-y).mean() # error = 0 is the  best model
    
    print(epoch, error)
    #break # print result of first loop for easy debugging

0 0.04085767418353488
1 -0.07761777274638039
2 0.06246498160686528
3 0.01040624498481292
4 -0.026295832742901634
5 -0.007124588336770392
6 0.0028326537732120804
7 -0.01629576707258473
8 0.058462311990106805
9 -0.10041360545149608
10 -0.0017797011417267667
11 -0.04546422808685691
12 0.023202095695320227
13 -0.10846193063133153
14 0.021982241124565816
15 -0.06630189453461263
16 0.03190508105381825
17 0.059349811427822356
18 -0.011686530662953583
19 -0.11953305686582133
20 0.02044807124648227
21 -0.018250278293089922
22 -0.004107342333873546
23 0.04178828550838737
24 -0.06273512941667475
25 -0.08759130165509894
26 -0.04883999087278013
27 -0.06575972354607316
28 -0.020316003534003445
29 0.03416090845141733
30 -0.11911198727192725
31 -0.08460424392643823
32 0.023962559842600473
33 -0.06347136846928238
34 0.06231637216009244
35 -0.06658127258830823
36 -0.0211779517363936
37 0.014282527908827065
38 0.019151954850609883
39 -0.08631588696252965
40 0.0566416322281513
41 -0.04305541907720941
42 -

In [70]:
## exception
y_example = [-1, 0, +1]
y_predict_example = [+1, -1, 0]

y_example = np.array(y_example)
y_predict_example = np.array(y_predict_example)

error = (y_predict_example-y_example).mean()
error


0.0

In [71]:
## Actually y_example and y_predicte_example are nor same, bur error is zero.
## To solve this problem, change (y_predict_example-y_example) plus values

np.abs(y_predict_example-y_example).mean()

1.3333333333333333

In [72]:
num_epoch = 100

for epoch in range(num_epoch):
    w1 = np.random.uniform(low = -1.0, high = 1.0)
    #w1 = 0.3  # for test 
    y_predict = w1 *x1 ## we expect w1 is 0.3
    
    error = np.abs(y_predict-y).mean() # Mean absolute error
    
    print(epoch, w1, error)
    #break # print result of first loop for easy debugging

0 -0.9162682413581955 0.6496841114503242
1 -0.07208862437559471 0.19875555332948824
2 0.6226048463484934 0.17232320619951463
3 0.9851221808560129 0.36596614148807627
4 0.1660322105153178 0.07156048420464117
5 0.22437249982617113 0.04039732649499733
6 -0.6593010545733309 0.5124220398601085
7 -0.30141018542864373 0.32125038593547617
8 0.859726338871881 0.2989844647421211
9 -0.06578399137123592 0.19538785880933596
10 0.1584257103991109 0.07562358648849771
11 -0.9387249529693102 0.6616796303934737
12 0.541655405226511 0.1290831018052677
13 0.05519913114135999 0.13076328852350103
14 0.13356256661188182 0.0889045297294636
15 0.47641406827714783 0.0942336676225204
16 -0.6645177770706543 0.5152086140754905
17 0.11188229189916377 0.10048530569135351
18 -0.9670438290925507 0.6768064940620127
19 -0.3652255102509412 0.35533809882173095
20 0.6162235378383356 0.16891455454822865
21 -0.5950812763720545 0.47811828340286366
22 0.7436572380833157 0.2369847774622416
23 0.21279317314921542 0.0465825612215

In [89]:
num_epoch = 1000000

best_error = 9999
best_w1 = None
best_w2 = None
best_b = None
best_epoch = None

for epoch in range(num_epoch):
    w1 = np.random.uniform(low = -1.0, high = 1.0)
    #w1 = 0.3  # for test 
    w2 = np.random.uniform(low = -1.0, high = 1.0)
    b = np.random.uniform(low = -1.0, high = 1.0)
    
    #y_predict = w1 *x1 ## we expect w1 is 0.3
    y_predict = w1 *x1 + w2 *x2 +b
    
    error = np.abs(y_predict-y).mean() # Mean absolute error
    
    if error < best_error:
        best_error = error
        best_w1 = w1
        best_w2 = w2
        best_b = b
        best_epoch = epoch
        print(f"{best_epoch}, w1 = {best_w1:.6f}, w2 = {best_w2:.6f}, b = {best_b:.6f}, error = {best_error:.6f}")
print("-----"*10)
print(f"{best_epoch}, w1 = {best_w1:.6f}, w2 = {best_w2:.6f}, b = {best_b:.6f}, error = {best_error:.6f}")

0, w1 = 0.795955, w2 = 0.757174, b = 0.562341, error = 0.603236
1, w1 = -0.686308, w2 = 0.992658, b = 0.230408, error = 0.545089
2, w1 = 0.376908, w2 = 0.280026, b = -0.304498, error = 0.290749
10, w1 = 0.087526, w2 = 0.720423, b = -0.198994, error = 0.240668
60, w1 = 0.405190, w2 = 0.164893, b = 0.041696, error = 0.180628
70, w1 = 0.183775, w2 = 0.327370, b = -0.055928, error = 0.106925
449, w1 = 0.115415, w2 = 0.442784, b = 0.070600, error = 0.105995
761, w1 = 0.283402, w2 = 0.516449, b = 0.098233, error = 0.096162
1044, w1 = 0.268079, w2 = 0.671358, b = -0.043693, error = 0.095217
1280, w1 = 0.385548, w2 = 0.592317, b = -0.007134, error = 0.060926
1811, w1 = 0.322041, w2 = 0.476169, b = 0.034139, error = 0.036957
4145, w1 = 0.333215, w2 = 0.552034, b = -0.001097, error = 0.030184
4755, w1 = 0.278214, w2 = 0.492948, b = 0.027506, error = 0.025617
72362, w1 = 0.275551, w2 = 0.516270, b = 0.010847, error = 0.015519
309826, w1 = 0.301330, w2 = 0.513863, b = 0.011275, error = 0.011206
42

### h-step search(2-6)

In [74]:
# num_epoch = 100
# h = 0.1

# #w1 = np.random.uniform(low = -1.0, high = 1.0)
# w1 = 0.0

# for epoch in range(num_epoch):
#     y_predict = w1 * x1
    
#     current_error = np.abs(y_predict - y).mean()
    
#     y_predict = (w1+h)* x1
#     h_plus_error = np.abs(y_predict - y).mean()
    
#     if h_plus_error < current_error:
#         w1 = w1+h
#         print(f"{epoch}, w1 = {w1:.6f}, error = {h_plus_error:.6f}")
#         continue
    
#     break
    
# print("-----"*10)
# print(f"{epoch}, w1 = {w1:.6f}, error = {current_error:.6f}")

0, w1 = 0.100000, error = 0.106832
1, w1 = 0.200000, error = 0.053416
2, w1 = 0.300000, error = 0.000000
--------------------------------------------------
3, w1 = 0.300000, error = 0.000000


In [75]:
num_epoch = 100
h = 0.1 ### must set up everytime

w1 = np.random.uniform(low = -1.0, high = 1.0)
#w1 = 0.0

for epoch in range(num_epoch):
    y_predict = w1 * x1
    
    current_error = np.abs(y_predict - y).mean()
    
    y_predict = (w1+h)* x1
    h_plus_error = np.abs(y_predict - y).mean()
    
    if h_plus_error < current_error:
        w1 = w1+h
        print(f"{epoch}, w1 = {w1:.6f}, error = {h_plus_error:.6f}")
        continue
    
        
    y_predict = (w1-h)* x1
    h_minus_error = np.abs(y_predict - y).mean()
    
    if h_minus_error < current_error:
        w1 = w1-h
        print(f"{epoch}, w1 = {w1:.6f}, error = {h_minus_error:.6f}")
        continue
    
    break
    
print("-----"*10)
print(f"{epoch}, w1 = {w1:.6f}, error = {current_error:.6f}")

0, w1 = 0.328702, error = 0.015332
--------------------------------------------------
1, w1 = 0.328702, error = 0.015332


### Gradient Descent(not yet)(2-7,8,9)

In [92]:
num_epoch = 100

w1 = np.random.uniform(low = -1.0, high = 1.0)
w2 = np.random.uniform(low = -1.0, high = 1.0)
b = np.random.uniform(low = -1.0, high = 1.0)


for epoch in range(num_epoch): 
    y_predict = w1 * x1 + w2 * x2 + b
    error = np.abs(y_predict-y).mean()
    
    if error < 0.0005:
        break
    ## update weights differentially
    w1 = w1 - ((y_predict - y)*x1).mean()
    w2 = w2 - ((y_predict - y)*x2).mean()
    b = b - ((y_predict - y)).mean() ## x3 is always 1
    
    print(f"{epoch}, w1 = {w1:.6f}, w2 = {w2:.6f}, b = {b:.6f}, error = {error:.6f}")
    
print("-----"*10)
print(f"{epoch}, w1 = {w1:.6f}, w2 = {w2:.6f}, b = {b:.6f}, error = {error:.6f}")

### more features available with gradient descent algorithm

0, w1 = 0.159102, w2 = -0.456131, b = 0.069370, error = 0.824195
1, w1 = 0.200561, w2 = -0.128972, b = 0.085893, error = 0.485645
2, w1 = 0.229643, w2 = 0.086338, b = 0.091369, error = 0.319434
3, w1 = 0.250462, w2 = 0.227903, b = 0.094800, error = 0.210341
4, w1 = 0.265264, w2 = 0.320996, b = 0.096892, error = 0.138541
5, w1 = 0.275732, w2 = 0.382222, b = 0.098162, error = 0.091262
6, w1 = 0.283099, w2 = 0.422496, b = 0.098926, error = 0.060127
7, w1 = 0.288264, w2 = 0.448991, b = 0.099383, error = 0.039619
8, w1 = 0.291871, w2 = 0.466424, b = 0.099653, error = 0.026109
9, w1 = 0.294383, w2 = 0.477896, b = 0.099810, error = 0.017209
10, w1 = 0.296127, w2 = 0.485446, b = 0.099901, error = 0.011345
11, w1 = 0.297334, w2 = 0.490416, b = 0.099951, error = 0.007482
12, w1 = 0.298169, w2 = 0.493688, b = 0.099979, error = 0.004937
13, w1 = 0.298744, w2 = 0.495842, b = 0.099993, error = 0.003258
14, w1 = 0.299140, w2 = 0.497261, b = 0.100000, error = 0.002150
15, w1 = 0.299412, w2 = 0.498195,

### Gradient Descent(2-10)

In [93]:
num_epoch = 100
learning_rate = 1.3 ## set up myself to control update speed --> hyperparameter --> deep learning algorithm performance

w1 = np.random.uniform(low = -1.0, high = 1.0)
w2 = np.random.uniform(low = -1.0, high = 1.0)
b = np.random.uniform(low = -1.0, high = 1.0)


for epoch in range(num_epoch): 
    y_predict = w1 * x1 + w2 * x2 + b
    error = np.abs(y_predict-y).mean()
    
    if error < 0.0005:
        break
    ## update weights differentially
    w1 = w1 - learning_rate * ((y_predict - y)*x1).mean()
    w2 = w2 - learning_rate * ((y_predict - y)*x2).mean()
    b = b - learning_rate * ((y_predict - y)).mean() ## x3 is always 1
    
    print(f"{epoch}, w1 = {w1:.6f}, w2 = {w2:.6f}, b = {b:.6f}, error = {error:.6f}")
    
print("-----"*10)
print(f"{epoch}, w1 = {w1:.6f}, w2 = {w2:.6f}, b = {b:.6f}, error = {error:.6f}")

### more features available with gradient descent algorithm

0, w1 = 0.335976, w2 = 0.244401, b = 0.023666, error = 0.276375
1, w1 = 0.325011, w2 = 0.356672, b = 0.108800, error = 0.141626
2, w1 = 0.310192, w2 = 0.421643, b = 0.088849, error = 0.073548
3, w1 = 0.305686, w2 = 0.456508, b = 0.099127, error = 0.040632
4, w1 = 0.302507, w2 = 0.476061, b = 0.097917, error = 0.021988
5, w1 = 0.301244, w2 = 0.486753, b = 0.099412, error = 0.012206
6, w1 = 0.300541, w2 = 0.492689, b = 0.099523, error = 0.006691
7, w1 = 0.300239, w2 = 0.495957, b = 0.099801, error = 0.003702
8, w1 = 0.300091, w2 = 0.497766, b = 0.099878, error = 0.002040
9, w1 = 0.300030, w2 = 0.498764, b = 0.099941, error = 0.001128
10, w1 = 0.300004, w2 = 0.499316, b = 0.099967, error = 0.000623
--------------------------------------------------
11, w1 = 0.300004, w2 = 0.499316, b = 0.099967, error = 0.000345
