# vectorization, np.dot, np.matmul

In [7]:
import numpy as np

In [8]:
a = np.random.rand(1000000)

In [9]:
b = np.random.rand(1000000)

In [10]:
%%time
s = 0

for i in range(1000000):
    s += a[i] + b[i]

s    

Wall time: 615 ms


999373.8138389728

In [11]:
%%time
s = np.dot(a,b)

s

Wall time: 973 µs


249717.18378186805

In [12]:
m = 2000
n = 1000
p = 1

In [13]:
x = np.random.rand(m,n)
x.shape

(2000, 1000)

In [14]:
v = np.random.rand(n, p)
v.shape

(1000, 1)

In [15]:
u = np.zeros((m,p))
u.shape

(2000, 1)

In [16]:
%%time
for i in range(m):
    for j in range(n):
        u[i] += x[i][j] * v[j]

u

Wall time: 6.1 s


array([[242.63518861],
       [241.68713929],
       [241.47765032],
       ...,
       [240.03375007],
       [243.49787954],
       [230.73571916]])

In [17]:
%%time
u = np.dot(x,v)
u

Wall time: 1.97 ms


array([[242.63518861],
       [241.68713929],
       [241.47765032],
       ...,
       [240.03375007],
       [243.49787954],
       [230.73571916]])

In [18]:
## exponetial

In [19]:
import math

In [20]:
n = 1000000

In [23]:
v = np.random.rand(n)
v.shape

(1000000,)

In [24]:
u = np.zeros((n, 1))
u

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]])

In [25]:
%%time
for i in range(n):
    u[i] = math.exp(v[i])
    
u

Wall time: 520 ms


array([[1.50621863],
       [1.37514349],
       [2.55946449],
       ...,
       [2.19471437],
       [2.56238249],
       [1.02390986]])

In [26]:
%%time
u = np.exp(v)
u

Wall time: 9 ms


array([1.50621863, 1.37514349, 2.55946449, ..., 2.19471437, 2.56238249,
       1.02390986])

In [27]:
np.log(v)

array([-0.89256861, -1.14395047, -0.06209026, ..., -0.24073244,
       -0.06087857, -3.74530186])

In [28]:
np.mean(v)

0.5006536778911356

In [29]:
np.min(v)

1.1492606928342752e-06

In [30]:
np.max(v)

0.9999981266971265

In [31]:
np.abs(v)

array([0.40960229, 0.31855808, 0.93979805, ..., 0.78605191, 0.94093749,
       0.0236285 ])

# numpy broadcasting

In [32]:
## vector + scala
## matrix + vector

#fitting dimension : broadcasting

In [34]:
x = np.array([[1,2,3,4]])

In [35]:
x+10

array([[11, 12, 13, 14]])

In [36]:
x = x.T
x

array([[1],
       [2],
       [3],
       [4]])

In [37]:
x+10

array([[11],
       [12],
       [13],
       [14]])

In [38]:
x = np.array([[1,4], [2,5],[3,6]])

In [43]:
y = np.array([[10,20,30]])
y = y.T
y

array([[10],
       [20],
       [30]])

In [44]:
x+y

array([[11, 14],
       [22, 25],
       [33, 36]])

In [45]:
y

array([[10],
       [20],
       [30]])

In [46]:
# axis = 0 ## column
# axis = 1 ## row

In [50]:
x = np.array([[1,4], [2,5],[3,6]])
x

array([[1, 4],
       [2, 5],
       [3, 6]])

In [51]:
x.mean()

3.5

In [52]:
x.mean(axis = 0)

array([2., 5.])

In [53]:
x.mean(axis = 1)

array([2.5, 3.5, 4.5])

In [62]:
x = np.array([1,2,3])
y = np.array([3,6,9])

In [63]:
x * y

array([ 3, 12, 27])

In [64]:
x ** y

array([    1,    64, 19683], dtype=int32)

In [65]:
np.dot(x, y)

42

In [66]:
np.cross(x, y)

array([0, 0, 0])

In [67]:
# error 
#np.sum(x, y)